# update
# upgrade

brew 'coreutils'
brew 'moreutils'
brew 'findutils'
brew 'elasticsearch'
brew 'postgresql'
brew 'git'
brew 'hub'
brew 'autoenv'
brew 'rbenv'
brew 'ruby-build'
brew 'node'
brew 'keybase'
brew 'leiningen'
brew 'openssl'
brew 'go'
brew 'redis'
brew 'imagemagick'
brew 'chromedriver'
brew 'pngquant'
brew 'reattach-to-user-namespace'
brew 'wget', args: ['enable-iri']
brew 'unrar'
brew 'tree'
brew 'the_silver_searcher'
brew 'watchman'
brew 'ctags'
brew 'tmux'
brew 'zsh'
brew 'heroku-toolbelt'
brew 'fzf', args: ['--HEAD']
brew 'vim'

tap 'neovim/neovim'
brew 'neovim', args: ['HEAD']

tap 'caskroom/cask'
cask '1password'
cask 'calibre'
cask 'fantastical'
cask 'dropbox'
cask 'google-chrome'
cask 'firefox'
cask 'sketch'
cask 'noizio'
cask 'slack'
cask 'vlc'
cask 'flux'
cask 'iterm2'
cask 'alfred'
cask 'sonos'

# cleanup
