# update
# upgrade

brew 'autoenv'
brew 'chromedriver'
brew 'coreutils'
brew 'elasticsearch'
brew 'emacs', args: ['with-cocoa', 'with-ctags', 'with-gnutls', 'with-imagemagick', 'with-librsvg', 'devel']
brew 'findutils'
brew 'fzf', args: ['HEAD']
brew 'git'
brew 'go'
brew 'heroku-toolbelt'
brew 'hub'
brew 'imagemagick'
brew 'keybase'
brew 'leiningen'
brew 'moreutils'
brew 'node'
brew 'openssl'
brew 'pngquant'
brew 'postgresql'
brew 'rbenv'
brew 'redis'
brew 'ruby-build'
brew 'the_silver_searcher'
brew 'tmux'
brew 'tree'
brew 'unrar'
brew 'vim'
brew 'watchman'
brew 'wget', args: ['enable-iri']
brew 'zsh'

tap 'caskroom/cask'
cask '1password'
cask 'alfred'
cask 'bartender'
cask 'calibre'
cask 'dash'
cask 'dropbox'
cask 'fantastical'
cask 'firefox'
cask 'flux'
cask 'google-chrome'
cask 'java'
cask 'karabiner'
cask 'noizio'
cask 'sketch'
cask 'slack'
cask 'sonos'
cask 'spectacle'
cask 'vlc'

tap 'homebrew/versions'
cask 'iterm2-nightly'

# cleanup
